services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
      - ./scripts:/app/scripts
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 2s
      retries: 30
  edge_node:
    build: ./edge_node
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./edge_node:/app/edge_node

    command: python main.py